import http from 'node:http';
import {readFileSync, existsSync, mkdirSync} from 'node:fs';
import {join, extname, normalize, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {DatabaseSync} from 'node:sqlite';

const ROOT=fileURLToPath(new URL('.', import.meta.url));
const PUBLIC=join(ROOT,'public');
const DATA=join(ROOT,'data');
mkdirSync(DATA,{recursive:true});
const DB_PATH=process.env.PATTERNWRIGHT_DB || join(DATA,'patternwright.db');
const PORT=Number(process.env.PORT||8787);
const HOST=process.env.HOST||'127.0.0.1';
const ADMIN_KEY=process.env.PATTERNWRIGHT_ADMIN_KEY||'';
const SCHEMA_VERSION=1;
const db=new DatabaseSync(DB_PATH);
db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS companies(id TEXT PRIMARY KEY, display_name TEXT NOT NULL, category TEXT, location TEXT, website TEXT, atlas_id TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, metadata_json TEXT NOT NULL DEFAULT '{}');
CREATE UNIQUE INDEX IF NOT EXISTS idx_companies_name ON companies(lower(display_name));
CREATE TABLE IF NOT EXISTS leads(id TEXT PRIMARY KEY, company_id TEXT, contact_name TEXT, email TEXT, phone TEXT, business_type TEXT, pain TEXT, frequency TEXT, software TEXT, stage TEXT NOT NULL, score INTEGER, estimated_value REAL NOT NULL DEFAULT 950, source TEXT, atlas_id TEXT, discovery_status TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, payload_json TEXT NOT NULL DEFAULT '{}', FOREIGN KEY(company_id) REFERENCES companies(id));
CREATE TABLE IF NOT EXISTS discovery(lead_id TEXT PRIMARY KEY, notes TEXT, saved_at TEXT, validated_at TEXT, brief_json TEXT NOT NULL DEFAULT '{}', FOREIGN KEY(lead_id) REFERENCES leads(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS proposals(id TEXT PRIMARY KEY, lead_id TEXT, business TEXT, text TEXT, price REAL, created_at TEXT NOT NULL, payload_json TEXT NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY, lead_id TEXT, business TEXT, progress INTEGER NOT NULL DEFAULT 0, tasks_json TEXT NOT NULL DEFAULT '[]', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, payload_json TEXT NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS atlas_profiles(id TEXT PRIMARY KEY,name TEXT NOT NULL,category TEXT,location TEXT,score INTEGER,primary_opportunity TEXT,profile_json TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS enrichment_jobs(id TEXT PRIMARY KEY,company_id TEXT,status TEXT NOT NULL,request_json TEXT NOT NULL,result_json TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_events(id INTEGER PRIMARY KEY AUTOINCREMENT,entity_type TEXT,entity_id TEXT,event TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL);
`);
db.prepare('INSERT OR REPLACE INTO meta(key,value) VALUES(?,?)').run('schema_version',String(SCHEMA_VERSION));
function parseAtlasPart(file,marker){
  const source=readFileSync(join(PUBLIC,'js',file),'utf8');
  const start=source.indexOf(marker); if(start<0) throw new Error(`Atlas seed marker missing in ${file}`);
  const a=source.indexOf('[',start), b=source.lastIndexOf(']');
  if(a<0||b<a) throw new Error(`Atlas seed malformed in ${file}`);
  return JSON.parse(source.slice(a,b+1));
}
function loadAtlasSeed(){ return [
  ...parseAtlasPart('atlas-data-1.js','const ATLAS_PART_1='),
  ...parseAtlasPart('atlas-data-2.js','const ATLAS_PART_2='),
  ...parseAtlasPart('atlas-data-3.js','const ATLAS_PART_3=')
];}
const atlasSeed=loadAtlasSeed();
const atlasCount=db.prepare('SELECT count(*) n FROM atlas_profiles').get().n;
if(!atlasCount){const ins=db.prepare('INSERT INTO atlas_profiles(id,name,category,location,score,primary_opportunity,profile_json,updated_at) VALUES(?,?,?,?,?,?,?,?)');const now=new Date().toISOString();db.exec('BEGIN');try{for(const p of atlasSeed)ins.run(p.id,p.name,p.category||'',p.location||'',p.score||null,p.primaryOpportunity||'',JSON.stringify(p),now);db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}}
function now(){return new Date().toISOString()}
function id(prefix){return `${prefix}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`}
function json(v){try{return JSON.parse(v||'{}')}catch{return {}}}
function reply(res,status,payload,headers={}){const body=typeof payload==='string'?payload:JSON.stringify(payload);res.writeHead(status,{'content-type':typeof payload==='string'?'text/plain; charset=utf-8':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...headers});res.end(body)}
async function body(req){const chunks=[];let n=0;for await(const c of req){n+=c.length;if(n>1_000_000)throw Object.assign(new Error('Body too large'),{status:413});chunks.push(c)}if(!chunks.length)return {};try{return JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{throw Object.assign(new Error('Invalid JSON'),{status:400})}}
function requireAdmin(req){if(!ADMIN_KEY)return true;return req.headers['x-patternwright-key']===ADMIN_KEY}
function audit(type,eid,event,detail={}){db.prepare('INSERT INTO audit_events(entity_type,entity_id,event,detail_json,created_at) VALUES(?,?,?,?,?)').run(type,eid,event,JSON.stringify(detail),now())}
function companyFor(name,category='',location='',atlasId=null){const existing=db.prepare('SELECT * FROM companies WHERE lower(display_name)=lower(?)').get(name);const ts=now();if(existing){db.prepare('UPDATE companies SET category=coalesce(nullif(?,\'\'),category), location=coalesce(nullif(?,\'\'),location), atlas_id=coalesce(?,atlas_id), updated_at=? WHERE id=?').run(category,location,atlasId,ts,existing.id);return existing.id}const cid=id('C');db.prepare('INSERT INTO companies(id,display_name,category,location,atlas_id,created_at,updated_at,metadata_json) VALUES(?,?,?,?,?,?,?,?)').run(cid,name,category,location,atlasId,ts,ts,'{}');return cid}
function atlasById(aid){const row=db.prepare('SELECT profile_json FROM atlas_profiles WHERE id=?').get(aid);return row?json(row.profile_json):null}
function atlasByName(name){const row=db.prepare('SELECT profile_json FROM atlas_profiles WHERE lower(name)=lower(?)').get(name);return row?json(row.profile_json):null}
function inferPattern(t){t=(t||'').toLowerCase();if(/lead|estimate|quote|roof|hvac|plumb|electric/.test(t))return 'Lead / estimate response loop';if(/maintenance|request|property|repair/.test(t))return 'Request intake router';if(/cater|event|booking|mobile/.test(t))return 'Structured event intake + coordination';if(/email|inbox/.test(t))return 'Inbox triage';if(/meeting|notes/.test(t))return 'Meeting-to-action';return 'Structured intake + follow-up'}
function reasoning(input){const lead=input.lead||input;const atlas=input.atlasId?atlasById(input.atlasId):lead.atlasId?atlasById(lead.atlasId):atlasByName(lead.business||'');if(atlas){return {provider:'rules-v1',evidence:(atlas.facts||[]).map(x=>({type:'public_fact',title:x.title,detail:x.detail,source:x.source||''})),issues:atlas.issues||[],pattern:atlas.primaryOpportunity||inferPattern(`${lead.business_type||''} ${lead.pain||''}`),metric:atlas.metric||'Handling time + completion rate',control:atlas.control||'Human approval for pricing, commitments, and exceptions',questions:atlas.discovery||[],hypotheses:atlas.hypotheses||[]}}
const pattern=inferPattern(`${lead.business_type||''} ${lead.pain||''}`);return {provider:'rules-v1',evidence:[],issues:[{title:lead.pain||'Workflow friction needs validation',detail:'Submitted by the prospect; validate the current-state process before proposing automation.',confidence:'medium'}],pattern,metric:'Handling time + completion rate',control:'Human approval for pricing, commitments, exceptions, and consequential customer-facing actions',questions:['Walk me through the process from trigger to completion.','Where is information copied or re-entered?','What gets delayed, forgotten, or escalated to the owner?','Which decisions must remain human?','What metric would prove the workflow improved?'],hypotheses:[]}}
function serializeState(){const leads=db.prepare('SELECT * FROM leads ORDER BY created_at DESC').all().map(r=>({...json(r.payload_json),id:r.id,createdAt:r.created_at,stage:r.stage,score:r.score,estimatedValue:r.estimated_value,name:r.contact_name||'',email:r.email||'',phone:r.phone||'',business_type:r.business_type||'',pain:r.pain||'',frequency:r.frequency||'',software:r.software||'',source:r.source||'',atlasId:r.atlas_id||undefined,discoveryStatus:r.discovery_status||undefined,business:json(r.payload_json).business||db.prepare('SELECT display_name FROM companies WHERE id=?').get(r.company_id)?.display_name||''}));const discovery={};for(const r of db.prepare('SELECT * FROM discovery').all())discovery[r.lead_id]={...json(r.brief_json),notes:r.notes||'',savedAt:r.saved_at||undefined,validatedAt:r.validated_at||undefined};const proposals=db.prepare('SELECT * FROM proposals ORDER BY created_at').all().map(r=>({...json(r.payload_json),id:r.id,leadId:r.lead_id,business:r.business,text:r.text,price:r.price,createdAt:r.created_at}));const projects=db.prepare('SELECT * FROM projects ORDER BY created_at').all().map(r=>({...json(r.payload_json),id:r.id,leadId:r.lead_id,business:r.business,progress:r.progress,tasks:json(r.tasks_json),createdAt:r.created_at}));const settings={};for(const r of db.prepare('SELECT * FROM settings').all())settings[r.key]=json(r.value_json).value;return {version:2.1,leads,projects,proposals,discovery,settings}}
function replaceState(s){const ts=now();db.exec('BEGIN');try{db.exec('DELETE FROM discovery; DELETE FROM proposals; DELETE FROM projects; DELETE FROM leads; DELETE FROM settings;');for(const l of s.leads||[]){const atlas=l.atlasId?atlasById(l.atlasId):null;const cid=companyFor(l.business||'Unnamed business',l.business_type||atlas?.category||'',atlas?.location||'',l.atlasId||null);db.prepare('INSERT INTO leads(id,company_id,contact_name,email,phone,business_type,pain,frequency,software,stage,score,estimated_value,source,atlas_id,discovery_status,created_at,updated_at,payload_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(l.id||id('L'),cid,l.name||'',l.email||'',l.phone||'',l.business_type||'',l.pain||'',l.frequency||'',l.software||'',l.stage||'New',l.score??null,Number(l.estimatedValue||950),l.source||'',l.atlasId||null,l.discoveryStatus||null,l.createdAt||ts,ts,JSON.stringify(l));}for(const [leadId,d] of Object.entries(s.discovery||{}))db.prepare('INSERT INTO discovery(lead_id,notes,saved_at,validated_at,brief_json) VALUES(?,?,?,?,?)').run(leadId,d.notes||'',d.savedAt||null,d.validatedAt||null,JSON.stringify(d));for(const p of s.proposals||[])db.prepare('INSERT INTO proposals(id,lead_id,business,text,price,created_at,payload_json) VALUES(?,?,?,?,?,?,?)').run(p.id||id('P'),p.leadId||null,p.business||'',p.text||'',Number(p.price||0),p.createdAt||ts,JSON.stringify(p));for(const p of s.projects||[])db.prepare('INSERT INTO projects(id,lead_id,business,progress,tasks_json,created_at,updated_at,payload_json) VALUES(?,?,?,?,?,?,?,?)').run(p.id||id('PR'),p.leadId||null,p.business||'',Number(p.progress||0),JSON.stringify(p.tasks||[]),p.createdAt||ts,ts,JSON.stringify(p));for(const [k,v] of Object.entries(s.settings||{}))db.prepare('INSERT INTO settings(key,value_json) VALUES(?,?)').run(k,JSON.stringify({value:v}));db.exec('COMMIT');audit('workspace','global','state_sync',{leads:(s.leads||[]).length})}catch(e){db.exec('ROLLBACK');throw e}}
function staticFile(req,res,pathname){
  if(pathname==='/os'){
    const body=readFileSync(join(PUBLIC,'os.html'),'utf8');
    res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin'});
    res.end(body);return true;
  }
  let target=pathname==='/'?join(PUBLIC,'index.html'):join(PUBLIC,normalize(pathname).replace(/^([/\\])+/,''));target=resolve(target);
  if(!target.startsWith(resolve(PUBLIC))||!existsSync(target))return false;
  const types={'.html':'text/html; charset=utf-8','.png':'image/png','.svg':'image/svg+xml','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8'};
  res.writeHead(200,{'content-type':types[extname(target)]||'application/octet-stream','cache-control':extname(target)==='.html'?'no-store':'public, max-age=3600','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin'});
  res.end(readFileSync(target));return true
}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);const p=u.pathname;if(p.startsWith('/api/') && p!='/api/fit-checks' && !requireAdmin(req))return reply(res,401,{error:'Admin key required'});
if(req.method==='GET'&&p==='/api/health')return reply(res,200,{ok:true,product:'Patternwright Production Core',schemaVersion:SCHEMA_VERSION,db:DB_PATH,atlasProfiles:db.prepare('SELECT count(*) n FROM atlas_profiles').get().n,time:now()});
if(req.method==='POST'&&p==='/api/fit-checks'){const d=await body(req);if(!String(d.business||'').trim()||!String(d.email||'').trim()||!String(d.pain||'').trim())return reply(res,400,{error:'business, email, and pain are required'});const atlas=atlasByName(String(d.business).trim());const cid=companyFor(String(d.business).trim(),d.business_type||atlas?.category||'',atlas?.location||'',atlas?.id||null);const lid=id('L'),ts=now();const payload={...d,business:String(d.business).trim()};db.prepare('INSERT INTO leads(id,company_id,contact_name,email,phone,business_type,pain,frequency,software,stage,score,estimated_value,source,atlas_id,discovery_status,created_at,updated_at,payload_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(lid,cid,d.name||'',d.email||'',d.phone||'',d.business_type||'',d.pain||'',d.frequency||'',d.software||'','New',null,950,d.source||'Website Fit Check',atlas?.id||null,'Not validated',d.submittedAt||ts,ts,JSON.stringify(payload));const r=reasoning({lead:{...payload,business_type:d.business_type||'',pain:d.pain||'',atlasId:atlas?.id},atlasId:atlas?.id});db.prepare('INSERT OR REPLACE INTO discovery(lead_id,notes,saved_at,validated_at,brief_json) VALUES(?,?,?,?,?)').run(lid,'',ts,null,JSON.stringify({preDiscovery:r,source:'Fit Check'}));audit('lead',lid,'fit_check_received',{business:d.business});return reply(res,201,{ok:true,leadId:lid,companyId:cid,atlasId:atlas?.id||null,preDiscovery:r});}
if(req.method==='GET'&&p==='/api/state')return reply(res,200,serializeState());
if(req.method==='PUT'&&p==='/api/state'){const d=await body(req);replaceState(d);return reply(res,200,{ok:true,syncedAt:now()});}
if(req.method==='GET'&&p==='/api/atlas'){const q=(u.searchParams.get('search')||'').toLowerCase();const rows=db.prepare('SELECT profile_json FROM atlas_profiles ORDER BY score DESC,name').all().map(r=>json(r.profile_json)).filter(x=>!q||`${x.name} ${x.category} ${x.location} ${(x.issues||[]).map(i=>i.title).join(' ')}`.toLowerCase().includes(q));return reply(res,200,{count:rows.length,profiles:rows});}
const am=p.match(/^\/api\/atlas\/([^/]+)$/);if(req.method==='GET'&&am){const a=atlasById(decodeURIComponent(am[1]));return a?reply(res,200,a):reply(res,404,{error:'Atlas profile not found'});}
if(req.method==='POST'&&p==='/api/atlas'){const a=await body(req);if(!a.id||!a.name)return reply(res,400,{error:'id and name required'});db.prepare('INSERT OR REPLACE INTO atlas_profiles(id,name,category,location,score,primary_opportunity,profile_json,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(a.id,a.name,a.category||'',a.location||'',a.score||null,a.primaryOpportunity||'',JSON.stringify(a),now());audit('atlas',a.id,'profile_upserted',{name:a.name});return reply(res,200,{ok:true,id:a.id});}
if(req.method==='POST'&&p==='/api/reason'){const d=await body(req);return reply(res,200,reasoning(d));}
if(req.method==='POST'&&p==='/api/enrichment/queue'){const d=await body(req),jid=id('E'),ts=now();db.prepare('INSERT INTO enrichment_jobs(id,company_id,status,request_json,result_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(jid,d.companyId||null,'queued',JSON.stringify(d),null,ts,ts);audit('enrichment',jid,'queued',d);return reply(res,201,{ok:true,jobId:jid,status:'queued'});}
if(req.method==='GET'&&p==='/api/enrichment/jobs'){const rows=db.prepare('SELECT * FROM enrichment_jobs ORDER BY created_at DESC').all().map(r=>({...r,request:json(r.request_json),result:r.result_json?json(r.result_json):null}));return reply(res,200,{jobs:rows});}
if(req.method==='GET'&&p==='/api/audit'){const rows=db.prepare('SELECT * FROM audit_events ORDER BY id DESC LIMIT 200').all().map(r=>({...r,detail:json(r.detail_json)}));return reply(res,200,{events:rows});}
if(staticFile(req,res,p))return;reply(res,404,{error:'Not found'});}catch(e){console.error(e);reply(res,e.status||500,{error:e.message||'Server error'})}});
server.listen(PORT,HOST,()=>console.log(`Patternwright Production Core running at http://${HOST}:${PORT}\nWebsite: http://${HOST}:${PORT}/\nOS: http://${HOST}:${PORT}/os\nDatabase: ${DB_PATH}`));
